In [134]:
import tensorflow as tf 


In [135]:
import pandas as pd 
import numpy as np 


In [136]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [137]:
df = df.drop(columns=['Surname'])
df = df.drop(columns=['Geography'])
df = df.drop(columns=['CustomerId'])

df = df.drop(columns=['RowNumber'])
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619  Female   42       2       0.00              1          1   
1          608  Female   41       1   83807.86              1          0   
2          502  Female   42       8  159660.80              3          1   
3          699  Female   39       1       0.00              2          0   
4          850  Female   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0

In [138]:
from sklearn.model_selection import train_test_split

x = df.drop(columns=['Exited'])
y =df['Exited']

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=1)


In [139]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['Gender']





0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int64

In [140]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0

1.Logastic Regression Classifier 

In [141]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(xtrain, ytrain)

ypred = model.predict(xtest)
accuracy_score(ypred,ytest)


ValueError: could not convert string to float: 'Male'

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


2.Knn Classifier 

In [ ]:

knn = KNeighborsClassifier()
knn.fit(xtrain, ytrain)
ypred = knn.predict(xtest)
print('Accuracy Score',accuracy_score(ytest, ypred))
print('Classification report',classification_report(ytest, ypred))


Accuracy Score 0.764
Classification report               precision    recall  f1-score   support

           0       0.80      0.94      0.86      1585
           1       0.29      0.10      0.14       415

    accuracy                           0.76      2000
   macro avg       0.55      0.52      0.50      2000
weighted avg       0.69      0.76      0.71      2000



In [ ]:
confusion_matrix(ytest, ypred)

array([[1538,   47],
       [ 236,  179]])

3.Simple vector Classfier 

In [ ]:
svc = SVC()
svc.fit(xtrain, ytrain)
ypred = svc.predict(xtest)
print('Accuracy Score',accuracy_score(ytest, ypred))
print('Classification report',classification_report(ytest, ypred))

Accuracy Score 0.7925
Classification report               precision    recall  f1-score   support

           0       0.79      1.00      0.88      1585
           1       0.00      0.00      0.00       415

    accuracy                           0.79      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.63      0.79      0.70      2000



/home/rohan/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rohan/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rohan/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
confusion_matrix(ytest, ypred)

array([[1538,   47],
       [ 236,  179]])

4.DecisionTree Classifier 

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(xtrain, ytrain)
ypred = dt.predict(xtest)

print('Accuracy Score',accuracy_score(ytest, ypred))
print('Classification report',classification_report(ytest, ypred))

Accuracy Score 0.7785
Classification report               precision    recall  f1-score   support

           0       0.86      0.86      0.86      1585
           1       0.47      0.48      0.48       415

    accuracy                           0.78      2000
   macro avg       0.67      0.67      0.67      2000
weighted avg       0.78      0.78      0.78      2000



In [ ]:
confusion_matrix(ytest, ypred)

array([[1538,   47],
       [ 236,  179]])

5.Naive Bayes classfier

In [ ]:
nbc = GaussianNB()
nbc.fit(xtrain, ytrain)
ypred = nbc.predict(xtest)

print('Accuracy Score',accuracy_score(ytest, ypred))
print('Classification report',classification_report(ytest, ypred))


Accuracy Score 0.783
Classification report               precision    recall  f1-score   support

           0       0.80      0.97      0.88      1585
           1       0.38      0.07      0.12       415

    accuracy                           0.78      2000
   macro avg       0.59      0.52      0.50      2000
weighted avg       0.71      0.78      0.72      2000



6.Random forest classfier

In [ ]:
rfc = RandomForestClassifier()
rfc.fit(xtrain, ytrain)
ypred = rfc.predict(xtest)
print('Accuracy Score',accuracy_score(ytest, ypred))
print('Classification report',classification_report(ytest, ypred))

0.852

In [ ]:
confusion_matrix(ytest, ypred)

array([[1538,   47],
       [ 236,  179]])

7.Gradient Boosting classfier 


In [ ]:
gbc = GradientBoostingClassifier()
gbc.fit(xtrain, ytrain)
ypred = gbc.predict(xtest)
print('Accuracy Score',accuracy_score(ytest, ypred))
print('Classification report',classification_report(ytest, ypred))


Accuracy Score 0.8585
Classification report               precision    recall  f1-score   support

           0       0.87      0.97      0.92      1585
           1       0.79      0.43      0.56       415

    accuracy                           0.86      2000
   macro avg       0.83      0.70      0.74      2000
weighted avg       0.85      0.86      0.84      2000



In [ ]:
confusion_matrix(ytest, ypred)

array([[1538,   47],
       [ 236,  179]])

Ann

In [ ]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()

xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)
xtrain_scaled

array([[-0.23082038,  0.91509065, -0.94449979, ..., -1.55337352,
         0.97725852,  0.42739449],
       [-0.25150912, -1.09278791, -0.94449979, ..., -1.55337352,
        -1.02327069, -1.02548708],
       [-0.3963303 , -1.09278791,  0.77498705, ...,  0.64376017,
         0.97725852, -0.94479772],
       ...,
       [ 0.22433188, -1.09278791,  0.58393295, ...,  0.64376017,
         0.97725852, -0.14096853],
       [ 0.13123255, -1.09278791,  0.01077067, ...,  0.64376017,
         0.97725852,  0.01781218],
       [ 1.1656695 ,  0.91509065,  0.29735181, ...,  0.64376017,
        -1.02327069, -1.15822478]])

In [ ]:
import tensorflow
from tensorflow import keras 
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.optimizers import Adam

In [ ]:
model = Sequential()
model.add(Dense(3,activation = 'sigmoid'))
model.add(Dense(1, activation = 'sigmoid'))


In [ ]:
model.compile(optimizer=Adam(),
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(xtrain_scaled, ytrain, epochs = 10)

Epoch 1/10
250/250 [==============================] - 1s 1ms/step - loss: 0.5279 - accuracy: 0.7949
Epoch 2/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4660 - accuracy: 0.8018
Epoch 3/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4481 - accuracy: 0.8009
Epoch 4/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4410 - accuracy: 0.8040
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4371 - accuracy: 0.8067
Epoch 6/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4345 - accuracy: 0.8083
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4326 - accuracy: 0.8106
Epoch 8/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4311 - accuracy: 0.8125
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4298 - accuracy: 0.8142
Epoch 10/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4287 - accuracy: 0.8159

In [ ]:
test_loss, test_accuracy = model.evaluate(xtest_scaled, ytest)
print('Test Loss:', test_loss)
print('Test Accuracy:', test_accuracy)

63/63 [==============================] - 0s 1ms/step - loss: 0.4274 - accuracy: 0.8090
Test Loss: 0.4273894131183624
Test Accuracy: 0.8090000152587891


In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (32, 3)                   30        
                                                                 
 dense_5 (Dense)             (32, 1)                   4         
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.layers[0].get_weights()

[array([[ 0.13057171,  0.22605786,  0.3189986 ],
        [ 0.5100892 ,  0.11128221, -0.4956517 ],
        [-1.8249644 , -1.3769014 ,  0.2206564 ],
        [ 0.01470806,  0.01625606, -0.04478328],
        [-0.48374525, -0.3565172 ,  0.31164885],
        [-0.12520368,  0.21187446,  0.13611643],
        [ 0.14210305, -0.06952258, -0.05998111],
        [-0.03859391,  0.64649576, -1.0770489 ],
        [ 0.02193637, -0.3436611 , -0.46038052]], dtype=float32),
 array([ 0.25481257,  0.44394824, -0.37186068], dtype=float32)]

In [ ]:
y_log = model.predict(xtest_scaled)

63/63 [==============================] - 0s 1ms/step


63/63 [==============================] - 0s 1ms/step


array([[0.13755903],
       [0.17342512],
       [0.14258946],
       ...,
       [0.05332982],
       [0.07563243],
       [0.31653008]], dtype=float32)

In [ ]:
test_loss, test_accuracy = model.evaluate(xtest, ytest)
print('Test accuracy',test_loss)
print('Test accuracy',test_accuracy)

63/63 [==============================] - 0s 2ms/step - loss: 0.6231 - accuracy: 0.6610
Test accuracy 0.6231054663658142
Test accuracy 0.6610000133514404


In [ ]:
ypred = model.predict(xtest_scaled)
ypred

63/63 [==============================] - 0s 995us/step


array([[0.13755903],
       [0.17342512],
       [0.14258946],
       ...,
       [0.05332982],
       [0.07563243],
       [0.31653008]], dtype=float32)

In [ ]:
xtest_scaled[0]

array([-1.03768121,  0.91509065,  0.77498705, -1.0482813 , -1.22599173,
        0.80225696,  0.64376017,  0.97725852, -0.05360571])

In [ ]:
y_pred = model.predict(xtest_scaled)
y_pred_labels = (y_pred > 0.5).astype(int).flatten()

63/63 [==============================] - 0s 1ms/step


In [ ]:
print('Accuracy Score:', accuracy_score(ytest, y_pred_labels))
print('Classification Report:\n', classification_report(ytest, y_pred_labels))
print('Confusion Matrix:\n', confusion_matrix(ytest, y_pred_labels))

Accuracy Score: 0.809
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.97      0.89      1585
           1       0.64      0.19      0.29       415

    accuracy                           0.81      2000
   macro avg       0.73      0.58      0.59      2000
weighted avg       0.78      0.81      0.76      2000

Confusion Matrix:
 [[1541   44]
 [ 338   77]]
